In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
df=sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x= df.drop('species', axis=1)
y= df['species']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
model_knn= KNeighborsClassifier(n_neighbors=13)
model_knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [13]:
model_knn.score(x_test, y_test)

1.0

In [16]:
from sklearn.svm import SVC

In [25]:
model_svm= SVC(gamma='auto')

In [22]:
model_svm.fit(x_train, y_train)

SVC(C=10, gamma='auto')

In [23]:
model_svm.score(x_test, y_test)

1.0

## Grid Search CV

In [24]:
from sklearn.model_selection import GridSearchCV

In [28]:
classifier= GridSearchCV((model_svm),{
    'C': [1, 10, 20,30],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}, cv=5, return_train_score=False)

In [29]:
classifier.fit(x, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly']})

In [31]:
classifier.cv_results_

{'mean_fit_time': array([0.00438566, 0.00484419, 0.00342822, 0.0028595 , 0.00199299,
        0.00300751, 0.00216641, 0.00194559, 0.00254483, 0.00214   ,
        0.00232105, 0.00445552, 0.00218506, 0.00271564, 0.00277686,
        0.00322943, 0.00151739, 0.00780602, 0.00252948, 0.00170016,
        0.00260215, 0.00188971, 0.00192785, 0.00770812]),
 'std_fit_time': array([4.87877038e-04, 9.08097165e-04, 1.02407533e-03, 4.52400560e-04,
        5.91739352e-07, 1.50148340e-03, 2.00768694e-04, 8.23879355e-04,
        6.34142927e-04, 2.18149242e-04, 3.56645679e-04, 2.31972834e-03,
        1.50070237e-04, 8.92144577e-04, 4.70791833e-04, 2.18447601e-04,
        3.42726189e-06, 5.84053323e-03, 2.88693165e-04, 5.56493500e-04,
        5.52810078e-04, 8.41794428e-04, 3.94961803e-04, 5.50561048e-03]),
 'mean_score_time': array([0.00338869, 0.00344434, 0.00335355, 0.00199356, 0.00179505,
        0.00211921, 0.00167894, 0.00223308, 0.0016273 , 0.00124969,
        0.00185571, 0.00174155, 0.00131426, 0.0021172 , 0.00210414,
        0.00193629, 0.00183163, 0.00140843, 0.00111513, 0.00174952,
        0.00143123, 0.00118747, 0.0011807 , 0.00144229]),
 'std_score_time': array([4.88480405e-04, 4.44816709e-04, 1.02389265e-03, 1.51240840e-06,
        3.97205782e-04, 3.47018732e-04, 4.82957707e-04, 6.86532455e-04,
        2.28717994e-04, 3.75335868e-04, 5.55693033e-04, 5.81985536e-04,
        4.74189455e-04, 3.47544012e-04, 6.67077181e-04, 6.08112441e-04,
        6.23794328e-04, 3.82880273e-04, 5.69806238e-05, 5.68700712e-04,
        5.01707089e-04, 7.56114949e-04, 1.91598926e-04, 5.28548009e-04]),
 'param_C': masked_array(data=[1, 1, 1, 1, 1, 1, 10, 10, 10, 10, 10, 10, 20, 20, 20,
                    20, 20, 20, 30, 30, 30, 30, 30, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_gamma': masked_array(data=['scale', 'scale', 'scale', 'auto', 'auto', 'auto',
                    'scale', 'scale', 'scale', 'auto', 'auto', 'auto',
                    'scale', 'scale', 'scale', 'auto', 'auto', 'auto',
                    'scale', 'scale', 'scale', 'auto', 'auto', 'auto'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'poly', 'linear', 'rbf', 'poly',
                    'linear', 'rbf', 'poly', 'linear', 'rbf', 'poly',
                    'linear', 'rbf', 'poly', 'linear', 'rbf', 'poly',
                    'linear', 'rbf', 'poly', 'linear', 'rbf', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1, 'gamma': 'auto', 'kernel': 'poly'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'poly'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 20, 'gamma': 'auto', 'kernel': 'poly'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 30, 'gamma': 'auto', 'kernel': 'poly'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        1.        , 1.        , 0.96666667, 1.        , 1.        ,
        0.96666667, 1.        , 1.        , 0.96666667, 1.        ,
        1.        , 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 1.        , 0.96666667, 0.96666667]),
 'split1_test_score': array([1.        , 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.96666667, 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.9       , 0.9       , 0.96666667, 0.9       , 0.9       ,
        0.96666667, 0.9       , 0.9       , 0.96666667, 0.9       ,
        0.9       , 0.9       , 0.9       , 0.9       , 0.93333333,
        0.9       , 0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.93333333, 0.93333333, 0.96666667, 0.93333333,
        0.93333333, 0.96666667, 0.93333333, 0.9       , 0.96666667,
        0.93333333, 0.9       , 0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.96666667, 0.98      , 0.98      , 0.98      ,
        0.96666667, 0.97333333, 0.98      , 0.96666667, 0.97333333,
        0.98      , 0.96666667, 0.96666667, 0.98      , 0.96666667,
        0.96666667, 0.96666667, 0.95333333, 0.96      , 0.97333333,
        0.96666667, 0.96      , 0.96      , 0.95333333]),
 'std_test_score': array([0.01632993, 0.02108185, 0.01632993, 0.01632993, 0.01632993,
        0.0421637 , 0.03887301, 0.01632993, 0.0421637 , 0.03887301,
        0.01632993, 0.0421637 , 0.0421637 , 0.01632993, 0.0421637 ,
        0.0421637 , 0.03651484, 0.03399346, 0.04898979, 0.02494438,
        0.0421637 , 0.04898979, 0.03887301, 0.03399346]),
 'rank_test_score': array([ 1, 12,  1,  1,  1, 12,  8,  1, 12,  8,  1, 12, 12,  1, 12, 12, 11,
        23, 20,  8, 12, 20, 20, 23], dtype=int32)}

In [32]:
results= pd.DataFrame(classifier.cv_results_)

In [33]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004386,4.878770e-04,0.003389,0.000488,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004844,9.080972e-04,0.003444,0.000445,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,12
2,0.003428,1.024075e-03,0.003354,0.001024,1,scale,poly,"{'C': 1, 'gamma': 'scale', 'kernel': 'poly'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002859,4.524006e-04,0.001994,0.000002,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.001993,5.917394e-07,0.001795,0.000397,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.003008,1.501483e-03,0.002119,0.000347,1,auto,poly,"{'C': 1, 'gamma': 'auto', 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,12
6,0.002166,2.007687e-04,0.001679,0.000483,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,8
7,0.001946,8.238794e-04,0.002233,0.000687,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
8,0.002545,6.341429e-04,0.001627,0.000229,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,12
9,0.002140,2.181492e-04,0.001250,0.000375,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,8
10,0.002321,3.566457e-04,0.001856,0.000556,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
11,0.004456,2.319728e-03,0.001742,0.000582,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,12
12,0.002185,1.500702e-04,0.001314,0.000474,20,scale,linear,"{'C': 20, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,12
13,0.002716,8.921446e-04,0.002117,0.000348,20,scale,rbf,"{'C': 20, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
14,0.002777,4.707918e-04,0.002104,0.000667,20,scale,poly,"{'C': 20, 'gamma': 'scale', 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,12
15,0.003229,2.184476e-04,0.001936,0.000608,20,auto,linear,"{'C': 20, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,12
16,0.001517,3.427262e-06,0.001832,0.000624,20,auto,rbf,"{'C': 20, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,11
17,0.007806,5.840533e-03,0.001408,0.000383,20,auto,poly,"{'C': 20, 'gamma': 'auto', 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,23
18,0.002529,2.886932e-04,0.001115,0.000057,30,scale,linear,"{'C': 30, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,20
19,0.001700,5.564935e-04,0.001750,0.000569,30,scale,rbf,"{'C': 30, 'gamma': 'scale', 'kernel': 'rbf'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,8
20,0.002602,5.528101e-04,0.001431,0.000502,30,scale,poly,"{'C': 30, 'gamma': 'scale', 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,12
21,0.001890,8.417944e-04,0.001187,0.000756,30,auto,linear,"{'C': 30, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,20
22,0.001928,3.949618e-04,0.001181,0.000192,30,auto,rbf,"{'C': 30, 'gamma': 'auto', 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,20
23,0.007708,5.505610e-03,0.001442,0.000529,30,auto,poly,"{'C': 30, 'gamma': 'auto', 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,23

In [35]:
results[['param_C', 'param_kernel', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

    param_C param_kernel  mean_test_score
0         1       linear         0.980000
2         1         poly         0.980000
3         1       linear         0.980000
4         1          rbf         0.980000
7        10          rbf         0.980000
10       10          rbf         0.980000
13       20          rbf         0.980000
6        10       linear         0.973333
9        10       linear         0.973333
19       30          rbf         0.973333
16       20          rbf         0.966667
1         1          rbf         0.966667
5         1         poly         0.966667
12       20       linear         0.966667
11       10         poly         0.966667
8        10         poly         0.966667
15       20       linear         0.966667
14       20         poly         0.966667
20       30         poly         0.966667
18       30       linear         0.960000
22       30          rbf         0.960000
21       30       linear         0.960000
17       20         poly         0.953333
23       30         poly         0.953333

## Random search cv

In [36]:
from sklearn.model_selection import RandomizedSearchCV

In [39]:
classifier_r= RandomizedSearchCV((model_svm),{
    'C': [1, 10, 20,30],
    'kernel': ['linear', 'rbf'],
},n_iter=4, cv=5, return_train_score=False)

In [40]:
classifier_r.fit(x, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['linear', 'rbf']})

In [42]:
results= pd.DataFrame(classifier_r.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001557,0.000459,0.000908,0.000473,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.016330,1
1,0.000845,0.000429,0.000283,0.000567,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.96,0.048990,3
2,0.000830,0.000417,0.000687,0.000574,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.96,0.038873,3
3,0.001065,0.000105,0.000812,0.000406,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.016330,1

In [43]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf             0.98
1       30       linear             0.96
2       30          rbf             0.96
3        1       linear             0.98